[env:esp32dev]
platform     = espressif32
board        = esp32dev
framework    = arduino
build_flags  = -O2 -std=c++17
monitor_speed = 115200
lib_deps     =
    Wire
    stm32duino/STM32duino VL53L5CX @ ^1.2.3
