[env:esp32dev]
platform    = espressif32
board       = esp32dev
framework   = arduino
build_flags = -O2 -std=c++17 -DCORE_DEBUG_LEVEL=0
monitor_speed = 2000000
lib_deps =
    Wire
    SPI
    stm32duino/STM32duino VL53L5CX @ ^1.2.3
